# Mi configuración para conectar la app con mi base de datos local
spring.application.name=practica_backend
spring.datasource.url=jdbc:mysql://localhost:3306/practica_final_backend?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para ver si algo falla
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Permitir que Flyway gestione la base de datos ya existente
# spring.flyway.baseline-on-migrate=true